version: 2

release:
  prerelease: auto
  mode: append

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?(?:[a-zA-Z]+-\d+ \| )?feat(?:\([[:word:]]+\))??!?:.+'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?(?:[a-zA-Z]+-\d+ \| )?fix(?:\([[:word:]]+\))??!?:.+'
      order: 1
    - title: Others
      order: 999